package com.mzh.financial.back.personinfo.dao;

import com.mzh.financial.back.personinfo.domain.TDataUser;
import com.mzh.financial.back.personinfo.domain.TDataUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TDataUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_user
     *
     * @mbg.generated Thu Feb 03 06:21:35 UTC 2022
     */
    long countByExample(TDataUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_user
     *
     * @mbg.generated Thu Feb 03 06:21:35 UTC 2022
     */
    int deleteByExample(TDataUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_user
     *
     * @mbg.generated Thu Feb 03 06:21:35 UTC 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_user
     *
     * @mbg.generated Thu Feb 03 06:21:35 UTC 2022
     */
    int insert(TDataUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_user
     *
     * @mbg.generated Thu Feb 03 06:21:35 UTC 2022
     */
    int insertSelective(TDataUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_user
     *
     * @mbg.generated Thu Feb 03 06:21:35 UTC 2022
     */
    List<TDataUser> selectByExample(TDataUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_user
     *
     * @mbg.generated Thu Feb 03 06:21:35 UTC 2022
     */
    TDataUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_user
     *
     * @mbg.generated Thu Feb 03 06:21:35 UTC 2022
     */
    int updateByExampleSelective(@Param("record") TDataUser record, @Param("example") TDataUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_user
     *
     * @mbg.generated Thu Feb 03 06:21:35 UTC 2022
     */
    int updateByExample(@Param("record") TDataUser record, @Param("example") TDataUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_user
     *
     * @mbg.generated Thu Feb 03 06:21:35 UTC 2022
     */
    int updateByPrimaryKeySelective(TDataUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_user
     *
     * @mbg.generated Thu Feb 03 06:21:35 UTC 2022
     */
    int updateByPrimaryKey(TDataUser record);
}